import "..styles/globals.css";
import Nav from "@/components/Nav";
import Script from "next/script";
<Script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
  strategy="afterInteractive"
/>

export const metadata = {
  title: "Abogada",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="holder">
            <div className="logo">
             <img src="/logo.png" width="100" alt="Abogada"/> 
             <h1>Abogada</h1>
            </div>
          </div>
        </header>
        {children}
        <Nav />
        <footer>
          <p>Derechos Reservados. Abogada</p>
        </footer>
      </body>
    </html>
  );
}
