import "@/styles/globals.css";
import Nav from "@/components/Nav";
import Script from "next/script";
import "@/styles/servicios.css";
import "@/styles/sobremi.css";
import "@/styles/home.css";
import "@/styles/contacto.css";
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: "Abogada",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <div className="footer">
        <footer>
          <p>Derechos Reservados. Abogada Maria Celeste Gomez</p>
        </footer>
        </div>

        <Script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
  strategy="afterInteractive"
/>
      </body>
    </html>
  );
}
