export const metadata = {
    title: "Abogada Maria :: Sobre mi",
    description: "destacadosGenerated by create next app"
};

export default function Sobremi() {
    return(
        <section className="holderSobremi">
            <div className="historia">
                <h2>Quien soy</h2>
                <div>
                    <p>Soy abogada egresada en el año 2019, con una profunda vocación por el Derecho Civil y la búsqueda de soluciones justas para mis clientes.</p>
                    <p>Desde el año 2021, he consolidado mi practica de manera independiente, lo que me permite brindar una atención personaliada, cercana y basada en la confianza mutua.</p>
                    <p>Mi compromiso con la excelencia me lleva a una formación constante. Recientemente, he profundizado mis conocimientos para ofrecer una defensa técnica de vanguardia en áreas sensibles y complejas del derecho actual.</p>
                </div>
            </div>
            <div className="Staff">
            <h2>Staff</h2>
            <div className="persona">
                <img src="abogada_120x120.png" width="75" alt="imagen1" />
                <h5>Dra. Maria Celeste Gomez</h5>
            <h6>Abogada Especialista en Derecho Civil</h6>
            <p><strong>2025:</strong> Especialización en Derecho Procesal Civil.</p>
            <p><strong>2024:</strong> Posgrado en Defensa Técnica de Niños, Niñas y Adolescentes.</p>
            <p><strong>2024:</strong> Diplomado en Derecho del Consumidor</p>
            </div>
            </div>
        </section>
    )
}