export const metadata = {
    title: "Abogada Maria :: Sobre mi",
    description: "destacadosGenerated by create next app"
};

export default function Sobremi() {
    return(
        <section className="holder">
            <div className="historia">
                <h2>Historia</h2>
                <div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae magna vel massa scelerisque pulvinar. Cras vel augue id massa dignissim feugiat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer posuere, lectus nec fermentum hendrerit, velit nunc porta erat, sed cursus lacus neque a lorem. Phasellus vel eros lorem. Duis nec risus sit amet nunc ultricies volutpat. Nullam sit amet aliquet lorem. Donec sit amet ipsum vel justo luctus lacinia. Suspendisse potenti.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae magna vel massa scelerisque pulvinar. Cras vel augue id massa dignissim feugiat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer posuere, lectus nec fermentum hendrerit, velit nunc porta erat, sed cursus lacus neque a lorem. Phasellus vel eros lorem. Duis nec risus sit amet nunc ultricies volutpat. Nullam sit amet aliquet lorem. Donec sit amet ipsum vel justo luctus lacinia. Suspendisse potenti.</p>
                </div>
            </div>
            <h2>Staff</h2>
            <div className="persona">
                <img src="abogada_120x120.png" width="75" alt="imagen1" />
                <h5>Maria</h5>
            <h6>Abogada en Derecho Civil</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae magna vel massa scelerisque pulvinar. Cras vel augue id massa dignissim feugiat.</p>
            </div>
        </section>
    )
}