export const metadata = {
    title: "Abogada Maria :: Sobre mi",
    description: "destacadosGenerated by create next app"
};

export default function Sobremi() {
    return(
        <section className="holderSobremi">
            <div className="historia">
                <h2>Acerca de mí</h2>
                <div>
                    <p>Soy abogada y acompaño a personas, emprendedores y profesionales que necesitan ordenar, resolver y tomar decisiones legales con claridad. Creo en el derecho como una herramienta práctica para destrabar conflictos y avanzar, no como un camino de desgaste innecesario.</p>
                    <p>Mi trabajo se enfoca en la negociación, los acuerdos extrajudiciales, la gestión estratégica de cobranzas y el análisis de situaciones crediticias, siempre con una mirada humana y realista. Me interesa que cada persona entienda su situación, conozca sus opciones y pueda elegir con tranquilidad.</p>
                    <p>Trabajo desde la cercanía, el compromiso y la confianza, buscando soluciones simples y efectivas que se adapten a cada caso y a cada historia.</p>
                </div>
            </div>
            <div className="Staff">
            <h2>Staff</h2>
            <div className="persona">
                <img src="fotostaff_150x150.jpeg" width="75" alt="imagenstaff" />
                <h5>Dra. Maria Celeste Gomez</h5>
            <h6>Abogada Especialista en Derecho Civil</h6>
            <p><strong>2025:</strong> Especialización en Derecho Procesal Civil.</p>
            <p><strong>2024:</strong> Posgrado en Defensa Técnica de Niños, Niñas y Adolescentes.</p>
            <p><strong>2024:</strong> Diplomado en Derecho del Consumidor</p>
            </div>
            </div>
        </section>
    )
}