export const metadata = {
    title: "Contacto",
    description: "destacadosGenerated by create next app"
};
import ContactForm from "@/components/ContactForm";
export default function Contacto() {

    return(
        <main className="holder contacto">
            <div className="columna">
                <h3>Complete el siguiente formulario</h3>
                <ContactForm />
            </div>
            <div className="columna datos">
                <h3>Otras vías de contacto</h3>
                <p>Tambien puede contactarse con nosotros utilizando los siguientes medios</p>
                <ul>
                    <li>Whatsapp:</li>
                    <li>Email:</li>
                    <li>Instagram:</li>
                </ul>
            </div>




        </main>




    )
}