export const metadata = {
    title: "Contacto",
    description: "destacadosGenerated by create next app"
};
import ContacForm from "@/components/ContactForm";
export default function Contacto() {

    return(
        <main className="holder contacto">
            <div className="columna">
                <h2>Complete el siguiente formulario</h2>
            </div>
            <div className="columna datos">
                <h2>Otras vías de contacto</h2>
                <p>Tambien puede contactarse con nosotros utilizando los siguientes medios</p>
                <ul>
                    <li>Telefono:</li>
                    <li>Email:</li>
                    <li>Instagram:</li>
                    <li>Fcebook:</li>
                </ul>
            </div>
            <ContacForm />




        </main>




    )
}