export const metadata = {
    title: "Abogada Maria :: Novedades",
    description: " destacadosGenerated by create next app"
};
import NovedadItem from "@/components/NovedadItem";
export default function Novedades() {
    return(
        <section className="holder">
            <h2>Novedades</h2>
            <NovedadItem />
        </section>
    )
}